platform :ios, '13.4'
require_relative '../node_modules/react-native/scripts/react_native_pods'

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage
  use_frameworks! :linkage => linkage.to_sym
end

use_modular_headers!

target 'app' do
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'appTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath], :mac_catalyst_enabled => false)
  end
end
